### ISSUE TITLE
Class 'Fans' not found in version 1.0.0.b7

### ISSUE THREAD

**Issue by tbernabero** [AstroPlant/astroplant-kit#3]
Hi all!!

When I try to configure the kit with fans peripherial I get the following error saying the class 'Fans' is not found:

Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]: Traceback (most recent call last):
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/astroplant_kit/kit.py", line 124, in _configure_peripherals
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     peripheral_class = self._modules[module_name].__dict__[class_name]
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]: KeyError: 'Fans'
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]: During handling of the above exception, another exception occurred:
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]: Traceback (most recent call last):
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/bin/astroplant-kit", line 78, in <module>
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     cli()
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     return self.main(*args, **kwargs)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     rv = self.invoke(ctx)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     return ctx.invoke(self.callback, **ctx.params)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     return callback(*args, **kwargs)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/bin/astroplant-kit", line 75, in run
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     trio.run(run)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/trio/_core/_run.py", line 1896, in run
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     raise runner.main_task_outcome.error
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/bin/astroplant-kit", line 73, in run
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     nursery.start_soon(kit.run)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/trio/_core/_run.py", line 741, in __aexit__
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     raise combined_error_from_nursery
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/astroplant_kit/kit.py", line 161, in run
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     await self.bootstrap()
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/astroplant_kit/kit.py", line 226, in bootstrap
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     self._configure(configuration)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/astroplant_kit/kit.py", line 89, in _configure
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     self._configure_peripherals(configuration["peripherals"])
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:   File "/home/pi/.local/lib/python3.7/site-packages/astroplant_kit/kit.py", line 128, in _configure_peripherals
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]:     % (class_name, module_name)
Aug 19 13:56:18 astroplant-kit astroplant-kit-start.sh[800]: ValueError: Could not find class 'Fans' in module 'astroplant_peripheral_device_library.pwm'
Aug 19 13:56:19 astroplant-kit systemd[1]: astroplant.service: Main process exited, code=exited, status=1/FAILURE

If I create a configuration without fans, everything works fine, but I'm unable to configure fans due to this error. Has anyone see something similar before? Many thanks!!

**Comment by SidneyNiccolson** [comment]
Hi @tbernabero,

I did not have this issue before. Attached some screenshots of my fan configuration, this might help to see if it is due to configuration. I'm running the same version of the software. 

![Screenshot from 2020-08-20 16-21-59](https://user-images.githubusercontent.com/8831506/90784233-593f1400-e301-11ea-8ef7-b3f0241321ca.png)
![Screenshot from 2020-08-20 16-21-33](https://user-images.githubusercontent.com/8831506/90784238-5b08d780-e301-11ea-96d6-c1dd648b04e7.png)

**Comment by SidneyNiccolson** [comment]
In addition take a look [here](https://github.com/AstroPlant/astroplant-peripheral-device-library/blob/master/astroplant_peripheral_device_library/pwm.py) and compare with your local version of the source code for the fans/pwm.py.

**Comment by tbernabero** [comment]
Thanks, @SidneyNiccolson. It seems is a issue related to the upgrade from 1.0.0b6 to 1.0.0.b7. The file pwm.py was the old one and not the latest. Maybe the upgrade procedure worked bad for me. I changed the file for the one in the repo and works fine. I'll check the upgrade procedure and repeat it again. Thanks for you help.

**Comment by tomcur** [comment]
This is probably because `astroplant-peripheral-device-library` (the repository @SidneyNiccolson linked) was not installed at version `1.0.0b4`. It is maintained separately from `astroplant-kit`.

I believe the latest image released is still at `1.0.0b3` of the peripheral library, and the instructions for manual installation on GitBook also refer to `1.0.0b3`. Which reminds me we should release a new version soon.

**Comment by tomcur** [comment]
Running e.g. the following upgrades the peripheral library to `1.0.0b4`.

```
$ python3 -m pip install git+https://github.com/AstroPlant/astroplant-peripheral-device-library@1.0.0b4
```

**Comment by tbernabero** [comment]
Hi, thanks @Beskhue. That is exactly the root cause of the problem. I did some test and I have seen that the image for downloading has the 1.0.0b3 version of the peripherial-device-library and upgrading to 1.0.0.b4 as you say solves the problem. I didn't see the latest version was 1.0.0b4 in the repo . Thanks for your help. Meanwhile, it would be helpfull for other people have the docs updated with the new version in the manual upgrade procedure. In https://astroplant-alpha.surge.sh/ also appears reference to 1.0.0.b3. Many thanks everyone for your help!!

**Comment by tomcur** [comment]
I updated the GitBook documentation and released a new kit image roughly a week ago, but forgot to close this issue. The image is available at https://astroplant.gitbook.io/join-mission/astroplant-software/software-setup.

It would be good to have a more robust version management system, e.g. currently the "Query kit version" RPC feature only queries the "kit core" software, and not the loaded peripheral libraries' versions. This is a feature that would be relatively difficult to implement neatly, though.
